name: simple_sms
description: "A modern MMS / SMS plugin for Android"
version: 0.0.1
homepage: simplezen.io

environment:
  sdk: ^3.7.0-0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_driver:
    sdk: flutter
  path: ^1.9.1
  flutter_local_notifications: ^19.4.2
  path_provider: ^2.1.5
  pigeon: ^26.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      dart:
        sdk: flutter
        pluginClass: SimpleSms
      android:
        package: io.simplezen.simple_sms
        pluginClass: SimpleSmsPlugin
      ios:
        pluginClass: SimpleSmsPlugin
