[versions]
activityKtx = "1.10.1"
agp = "8.9.1"
appcompat = "1.7.0"
commonsCodec = "1.18.0"
concurrentFutures = "1.2.0"
coreKtx = "1.16.0"
coreRole = "1.1.0"
fragmentKtx = "1.8.6"
guava = "33.4.8-android"
junit = "4.13.2"
material = "1.12.0"
mockitoCore = "5.4.0"
workVersion = "2.10.0"
annotation = "1.9.1"
fragment = "1.8.6"
kotlin = "2.1.20"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-core = { module = "androidx.core:core", version.ref = "coreKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "coreRole" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "workVersion" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workVersion" }
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "workVersion" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workVersion" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }